services:
  - type: web
    name: shopy
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn Shopy.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Shopy.settings
